### ISSUE TITLE
Question: Use with `Vue.use(modal)`

### ISSUE THREAD

**Issue by karlpokus** [colinf/modal-vue#1]
Hi!

This is **not an issue**. Just a question. Did you consider using `Vue.use()` when registering the component? I see other vue modules use this pattern. Curious.

**Comment by colinf** [comment]
Hi Karl,

Sorry for the delay in replying - I've had a busy week. I think Vue.use() is really intended for registering plugins as opposed to components. As this was just a simple component I didn't go down that route.

Cheers,
  Colin

**Comment by karlpokus** [comment]
Sounds reasonable. Is there a simple way to determine what is a *component* vs *plugin*?

**Comment by colinf** [comment]
The link below is probably the best guidance, although it does say there is no strictly defined scope!

[https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin](https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin)

**Comment by karlpokus** [comment]
cool. Thank you!
